version: '3.7'
services:
  db:
    container_name: postgres
    restart: always
    image: postgres:latest
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: carcatcher
    ports:
      - "5555:5432"
    volumes:
      - carcatcher:/data/postgres

volumes:
  carcatcher:
